def getGossipStones():
    return ['Colossus (Spirit Temple)',
            'DMC (Bombable Wall)',
            'DMC (Upper Grotto)',
            'DMT (Biggoron)',
            'DMT (Storms Grotto)',
            'Dodongos Cavern (Bombable Wall)',
            'GC (Maze)',
            'GC (Medigoron)',
            'GV (Waterfall)',
            'Graveyard (Shadow Temple)',
            'HC (Malon)',
            'HC (Rock Wall)',
            'HC (Storms Grotto)',
            'HF (Cow Grotto)',
            'HF (Near Market Grotto)',
            'HF (Open Grotto)',
            'HF (Southeast Grotto)',
            'KF (Deku Tree Left)',
            'KF (Deku Tree Right)',
            'KF (Outside Storms)',
            'KF (Storms Grotto)',
            'Kak (Open Grotto)',
            'LH (Lab)',
            'LH (Southeast Corner)',
            'LH (Southwest Corner)',
            'LW (Bridge)',
            'LW (Near Shortcuts Grotto)',
            'SFM (Maze Lower)',
            'SFM (Maze Upper)',
            'SFM (Saria)',
            'ToT (Left)',
            'ToT (Left-Center)',
            'ToT (Right)',
            'ToT (Right-Center)',
            'ZD (Mweep)',
            'ZF (Fairy)',
            'ZF (Jabu)',
            'ZR (Near Domain)',
            'ZR (Near Grottos)',
            'ZR (Open Grotto)']
